version: "3.8"

services:
  looger:
    image: 019370700520.dkr.ecr.ap-southeast-2.amazonaws.com/docker/looger:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
